<div class="row clearfix">
	<div class="col-md-12 column">
	
		<div id="canvas_holder">
			<div id="map_canvas"></div>
		</div>
		<h3 class="text-center">
			
			
		</h3>
	</div>
</div>

<div class="container">

	<div class="row clearfix" style="text-align:center">
		<div class="col-md-4 column">
		
			<div class="thumbnail" height='100px;'>
				<img width="160" height="100" alt="300x200" src="http://new.static.ebay.com.au/cache/windows/Images/Merch/Images/281213449211_130398945915031250_srv-canvasresize_200-200-85-200-200-FFF.jpg" />
				<div class="caption">
					<p>
						Abercrombie & Fitch Men Sentinel Range Hoodie Moose Full-Zip Jacket -$0 Shipping
					</p>
					<p style='color:#990000'>
						R$ 19,30 
					</p>
					<p>
						<a class="btn btn-primary" href="#">Localizar</a>
					</p>
				</div>
			</div>
			<div class="thumbnail" height='100px;'>
				<img width="160" height="100" alt="300x200" src="http://thumbs1.ebaystatic.com/d/l200/m/mS1WAeFwBNNGHdlBC_HsrxA.jpg" />
				<div class="caption">
					<p>
						Diamant Ring 585 Weißgold Damenring Brillanten
					</p>
					<p style='color:#990000'>
						R$ 19,30 
					</p>
					<p>
						<a class="btn btn-primary" href="#">Localizar</a>
					</p>
				</div>
			</div>
		</div>
		<div class="col-md-8 column">
			
		
				<div class="thumbnail" style='height:100%;'>
					<img width="181" height="130" alt="300x200" src="http://new.static.ebay.com.au/cache/windows/Images/Merch/Images/151413022492_130562327520839297_srv-canvasresize_276-276-85-276-276-FFF.jpg" />
					<div class="caption">
						<p>
							
							Novo Original Samsung Galaxy Gear 1 Relógio Fone SmartWatch Sm V700 S Ouro Rosa Pacote de varejo
						
						</p>
						<p style='color:#990000'>
							R$ 13,90

						</p>
						<p>
							<a class="btn btn-primary" href="#">Localizar</a>
						</p>
					</div>
				</div>
			
				<div class="col-md-6 column">
					<div class="thumbnail" height='100px;' width='50px;'>
						<img width="160" height="100" alt="300x200" src="http://new.static.ebay.com.au/cache/windows/Images/Merch/Images/281213449211_130398945915031250_srv-canvasresize_200-200-85-200-200-FFF.jpg" />
						<div class="caption">
							<p>
								Abercrombie & Fitch Men Sentinel Range Hoodie Moose Full-Zip Jacket -$0 Shipping
							</p>
							<p style='color:#990000'>
								R$ 19,30 
							</p>
							<p>
								<a class="btn btn-primary" href="#">Localizar</a>
							</p>
						</div>
					</div>
				</div>
				
				<div class="col-md-6 column">
					<div class="thumbnail" height='100px;' width='50px;'>
						<img width="160" height="100" alt="300x200" src="http://new.static.ebay.com.au/cache/windows/Images/Merch/Images/281213449211_130398945915031250_srv-canvasresize_200-200-85-200-200-FFF.jpg" />
						<div class="caption">
							<p>
								Abercrombie & Fitch Men Sentinel Range Hoodie Moose Full-Zip Jacket -$0 Shipping
							</p>
							<p style='color:#990000'>
								R$ 19,30 
							</p>
							<p>
								<a class="btn btn-primary" href="#">Localizar</a>
							</p>
						</div>
					</div>
				</div>
			
		</div>
	</div>
	
	
	<div class="row clearfix" style="text-align:center">
		<div class="col-md-4 column">
		
			<div class="thumbnail">
				<img width="160" height="100" alt="300x200" src="http://new.static.ebay.com.au/cache/windows/Images/Merch/Images/291142396474_130552093222685000_srv-canvasresize_200-200-85-200-200-FFF.jpg" />
				<div class="caption">
					<p>
						Samsung Galaxy S5 SM-G900F 4G LTE 16GB Smartphone (Unlocked) - Charcoal Black
					</p>
					<p style='color:#990000'>
						R$ 1.189,78

					</p>
					<p>
						<a class="btn btn-primary" href="#">Localizar</a>
					</p>
				</div>
			</div>
		</div>
		<div class="col-md-4 column">
		
			<div class="thumbnail">
				<img width="160" height="100" alt="300x200" src="http://assets.hellofood.com.br/layout/themes/margherita/images/br/homepage-2-2.png?v=20140806104933" />
				<div class="caption">
					<p>
						Parmegiana Frango
					</p>
					<p style='color:#990000'>
						R$ 13,90

					</p>
					<p>
						<a class="btn btn-primary" href="#">Localizar</a>
					</p>
				</div>
			</div>
		</div>
		<div class="col-md-4 column">
		
			<div class="thumbnail">
				<img width="160" height="100" alt="300x200" src="http://assets.hellofood.com.br/layout/themes/margherita/images/br/homepage-2-2.png?v=20140806104933" />
				<div class="caption">
					<p>
						Parmegiana Frango
					</p>
					<p style='color:#990000'>
						R$ 13,90

					</p>
					<p>
						<a class="btn btn-primary" href="#">Localizar</a>
					</p>
				</div>
			</div>
		</div>
	</div>
	
	
	<div class="row clearfix" style="text-align:center">
		<div class="col-md-4 column">
		
			<div class="thumbnail">
				<img width="160" height="100" alt="300x200" src="http://assets.hellofood.com.br/layout/themes/margherita/images/br/homepage-2-2.png?v=20140806104933" />
				<div class="caption">
					<p>
						Parmegiana Frango
					</p>
					<p style='color:#990000'>
						R$ 13,90

					</p>
					<p>
						<a class="btn btn-primary" href="#">Localizar</a>
					</p>
				</div>
			</div>
			
		</div>
		<div class="col-md-4 column">

			<div class="thumbnail">
				<img width="160" height="100" alt="300x200" src="http://assets.hellofood.com.br/layout/themes/margherita/images/br/homepage-2-2.png?v=20140806104933" />
				<div class="caption">
					<p>
						Parmegiana Frango
					</p>
					<p style='color:#990000'>
						R$ 13,90

					</p>
					<p>
						<a class="btn btn-primary" href="#">Localizar</a>
					</p>
				</div>
			</div>
			
		</div>
		<div class="col-md-4 column">
		
			<div class="thumbnail">
				<img width="160" height="100" alt="300x200" src="http://assets.hellofood.com.br/layout/themes/margherita/images/br/homepage-2-2.png?v=20140806104933" />
				<div class="caption">
					<p>
						Parmegiana Frango
					</p>
					<p style='color:#990000'>
						R$ 13,90

					</p>
					<p>
						<a class="btn btn-primary" href="#">Localizar</a>
					</p>
				</div>
			</div>
			
		</div>
	</div>
	
</div>