<?php echo $this->doctype(); ?>

<!DOCTYPE html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Quero')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')	
            ->prependFile($this->basePath() . '/js/less-1.3.3.min.js')
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',)); 
           
        ?>
		
		<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
		
		<script type="text/javascript">
		                                                                                                                                    
		    function googleMaps() {
				var latLng = new google.maps.LatLng(-16.6811472, -49.2434212);
				
				var myOptions = {
					panControl: false,
					zoomControl: true,
					zoomControlOptions: {
						style: google.maps.ZoomControlStyle.SMALL,
						position: google.maps.ControlPosition.LEFT_CENTER
					},
					mapTypeControl: true,
					scaleControl: false,
					streetViewControl: true,
					overviewMapControl: false,
					draggable: true,
					disableDoubleClickZoom: false, //disable zooming
					scrollwheel: true,
					zoom: 12,
					center: latLng,
					mapTypeId: google.maps.MapTypeId.ROADMAP // ROADMAP; SATELLITE; HYBRID; TERRAIN;
				};
				
				map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

			
<?php 
			$cont = 0;
			foreach ($listaProdutos as $produto) :
?>
						
				var latLng<?php echo $cont ?> = new google.maps.LatLng(<?php echo $produto['latitude']; ?>,	<?php echo $produto['longitude']; ?>);
					  
				var marker<?php echo $cont ?> = new google.maps.Marker({
				      position: latLng<?php echo $cont ?>,
				      map: map,
				      title:"<?php echo $produto['ds_produto']; ?>"
				  });
						
<?php  
			$cont = $cont + 1;
			endforeach;  
?>
					
			}
			
		    $(function(){
		    	googleMaps();
		    });
		    
    	</script>
	
		<style type="text/css">
		    #canvas_holder{
				left: 0px;
				width:100%;
				height:100%;
				z-index: -1;
		    }
		    #map_canvas{
				width:100%;
				height:400px;
		    }
			.navbar-default {
				background-color: #F6F7F7;
				border-color: #F6F7F7;
			}
	    </style>

    </head>
<body style="background-color:#F6F7F7">

	<div class="row clearfix">
		<div class="col-md-12 column">
			<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
				<div class="navbar-header">
					 <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button> <a class="navbar-brand" href="#">Brand</a>
				</div>
				
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li class="active">
							<a href="#">Link</a>
						</li>
						<li>
							<a href="#">Link</a>
						</li>
						<li class="dropdown">
							 <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<strong class="caret"></strong></a>
							<ul class="dropdown-menu">
								<li>
									<a href="#">Action</a>
								</li>
								<li>
									<a href="#">Another action</a>
								</li>
								<li>
									<a href="#">Something else here</a>
								</li>
								<li class="divider">
								</li>
								<li>
									<a href="#">Separated link</a>
								</li>
								<li class="divider">
								</li>
								<li>
									<a href="#">One more separated link</a>
								</li>
							</ul>
						</li>
					</ul>
					<form class="navbar-form navbar-left" role="search">
						<div class="form-group">
							<input type="text" class="form-control">
						</div> <button type="submit" class="btn btn-default">Buscar</button>
					</form>
					<ul class="nav navbar-nav navbar-right">
						<li>
							<a href="#">Link</a>
						</li>
						<li class="dropdown">
							 <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<strong class="caret"></strong></a>
							<ul class="dropdown-menu">
								<li>
									<a href="#">Action</a>
								</li>
								<li>
									<a href="#">Another action</a>
								</li>
								<li>
									<a href="#">Something else here</a>
								</li>
								<li class="divider">
								</li>
								<li>
									<a href="#">Separated link</a>
								</li>
							</ul>
						</li>
					</ul>
				</div>
				
			</nav>
		</div>
	</div>
	
	
	
	
	
	
	<div class="row clearfix">
		<div class="col-md-12 column">
		
			<div id="canvas_holder">
				<div id="map_canvas"></div>
			</div>
			<h3 class="text-center">
				
				
			</h3>
		</div>
	</div>
	
		
	
	<div class="container">
	
	
		<div class="row clearfix" style="text-align:center">
			<div class="col-md-4 column">
			
				<div class="thumbnail" height='100px;'>
					<img width="160" height="100" alt="300x200" src="<?php echo $this->basePath() . '/img/semfoto.gif' ?>" />
					<div class="caption">
						<p>
							<?php echo $dadosPagina['titulo1']; ?>
						</p>
						<p style='color:#990000'>
							R$ <?php echo $dadosPagina['preco1']; ?>
						</p>
						<p>
							<a class="btn btn-primary" href="#">Localizar</a>
						</p>
					</div>
				</div>
				<div class="thumbnail" height='100px;'>
					<img width="160" height="100" alt="300x200" src="<?php echo $this->basePath() . '/img/semfoto.gif' ?>" />
					<div class="caption">
						<p>
							<?php echo $dadosPagina['titulo2']; ?>
						</p>
						<p style='color:#990000'>
							R$ <?php echo $dadosPagina['preco2']; ?>
						</p>
						<p>
							<a class="btn btn-primary" href="#">Localizar</a>
						</p>
					</div>
				</div>
			</div>
			<div class="col-md-8 column">
				
			
					<div class="thumbnail" style='height:100%;'>
						<img width="181" height="130" alt="300x200" src="<?php echo $this->basePath() . '/img/semfoto.gif' ?>" />
						<div class="caption">
							<p>
								
								<?php echo $dadosPagina['titulo3']; ?>
							
							</p>
							<p style='color:#990000'>
								R$ <?php echo $dadosPagina['preco3']; ?>
	
							</p>
							<p>
								<a class="btn btn-primary" href="#">Localizar</a>
							</p>
						</div>
					</div>
				
					<div class="col-md-6 column">
						<div class="thumbnail" height='100px;' width='50px;'>
							<img width="160" height="100" alt="300x200" src="<?php echo $this->basePath() . '/img/semfoto.gif' ?>" />
							<div class="caption">
								<p>
									<?php echo $dadosPagina['titulo4']; ?>
								</p>
								<p style='color:#990000'>
									R$ <?php echo $dadosPagina['preco4']; ?>
								</p>
								<p>
									<a class="btn btn-primary" href="#">Localizar</a>
								</p>
							</div>
						</div>
					</div>
					
					<div class="col-md-6 column">
						<div class="thumbnail" height='100px;' width='50px;'>
							<img width="160" height="100" alt="300x200" src="<?php echo $this->basePath() . '/img/semfoto.gif' ?>" />
							<div class="caption">
								<p>
									<?php echo $dadosPagina['titulo5']; ?>
								</p>
								<p style='color:#990000'>
									<?php echo $dadosPagina['preco5']; ?>
								</p>
								<p>
									<a class="btn btn-primary" href="#">Localizar</a>
								</p>
							</div>
						</div>
					</div>
				
			</div>
		</div>
		
		
		<div class="row clearfix" style="text-align:center">
			<div class="col-md-4 column">
			
				<div class="thumbnail">
					<img width="160" height="100" alt="300x200" src="<?php echo $this->basePath() . '/img/semfoto.gif' ?>" />
					<div class="caption">
						<p>
							<?php echo $dadosPagina['titulo6']; ?>
						</p>
						<p style='color:#990000'>
							R$ <?php echo $dadosPagina['preco6']; ?>
	
						</p>
						<p>
							<a class="btn btn-primary" href="#">Localizar</a>
						</p>
					</div>
				</div>
			</div>
			<div class="col-md-4 column">
			
				<div class="thumbnail">
					<img width="160" height="100" alt="300x200" src="<?php echo $this->basePath() . '/img/semfoto.gif' ?>" />
					<div class="caption">
						<p>
							<?php echo $dadosPagina['titulo7']; ?>
						</p>
						<p style='color:#990000'>
							R$ <?php echo $dadosPagina['preco7']; ?>
	
						</p>
						<p>
							<a class="btn btn-primary" href="#">Localizar</a>
						</p>
					</div>
				</div>
			</div>
			<div class="col-md-4 column">
			
				<div class="thumbnail">
					<img width="160" height="100" alt="300x200" src="<?php echo $this->basePath() . '/img/semfoto.gif' ?>" />
					<div class="caption">
						<p>
							<?php echo $dadosPagina['titulo8']; ?>
						</p>
						<p style='color:#990000'>
							R$ <?php echo $dadosPagina['preco8']; ?>
	
						</p>
						<p>
							<a class="btn btn-primary" href="#">Localizar</a>
						</p>
					</div>
				</div>
			</div>
		</div>
		
		
		<div class="row clearfix" style="text-align:center">
			<div class="col-md-4 column">
			
				<div class="thumbnail">
					<img width="160" height="100" alt="300x200" src="<?php echo $this->basePath() . '/img/semfoto.gif' ?>" />
					<div class="caption">
						<p>
							<?php echo $dadosPagina['titulo9']; ?>
						</p>
						<p style='color:#990000'>
							R$ <?php echo $dadosPagina['preco9']; ?>
	
						</p>
						<p>
							<a class="btn btn-primary" href="#">Localizar</a>
						</p>
					</div>
				</div>
				
			</div>
			<div class="col-md-4 column">
	
				<div class="thumbnail">
					<img width="160" height="100" alt="300x200" src="<?php echo $this->basePath() . '/img/semfoto.gif' ?>" />
					<div class="caption">
						<p>
							<?php echo $dadosPagina['titulo10']; ?>
						</p>
						<p style='color:#990000'>
							R$ <?php echo $dadosPagina['preco10']; ?>
	
						</p>
						<p>
							<a class="btn btn-primary" href="#">Localizar</a>
						</p>
					</div>
				</div>
				
			</div>
			<div class="col-md-4 column">
			
				<div class="thumbnail">
					<img width="160" height="100" alt="300x200" src="<?php echo $this->basePath() . '/img/semfoto.gif' ?>" />
					<div class="caption">
						<p>
							<?php echo $dadosPagina['titulo11']; ?>
						</p>
						<p style='color:#990000'>
							R$ <?php echo $dadosPagina['preco11']; ?>
	
						</p>
						<p>
							<a class="btn btn-primary" href="#">Localizar</a>
						</p>
					</div>
				</div>
				
			</div>
		</div>
		
	</div>
	
	
	
		
	
	
	<footer style="background-color:#252525" >
			<div class="container inner">
				<div class="row">
					
					<div class="col-md-3 col-sm-6 inner">
						<h4 style="color:white; font-family:sans-serif">Who we are</h4>
						<a href="index.html"><img alt="" src="assets/images/logo-white.svg" class="logo img-intext"></a>
						<p style="color:#a3b1bf">Magnis modipsae voloratati andigen daepeditem quiate re porem que aut labor. Laceaque eictemperum quiae sitiorem rest non restibusaes maio es dem tumquam.</p>
						<a class="txt-btn" href="about.html">More about us</a>
					</div><!-- /.col -->
					
					<div class="col-md-3 col-sm-6 inner">
						<h4 style="color:white; font-family:sans-serif">Latest works</h4>	
					</div><!-- /.col -->
					
					
					<div class="col-md-3 col-sm-6 inner">
						<h4 style="color:white; font-family:sans-serif">Get In Touch</h4>
						<p style="color:#a3b1bf">Doloreiur quia commolu ptatemp dolupta oreprerum tibusam eumenis et consent accullignis dentibea autem inisita.</p>
						<ul class="contacts">
							<li><i class="icon-location contact"></i> 84 Street, City, State 24813</li>
							<li><i class="icon-mobile contact"></i> +00 (123) 456 78 90</li>
							<li><a href="#"><i class="icon-mail-1 contact"></i> info@reen.com</a></li>
						</ul><!-- /.contacts -->
					</div><!-- /.col -->
					
					<div class="col-md-3 col-sm-6 inner">
						<h4 style="color:white; font-family:sans-serif">Contato</h4>
						
							<img alt="" src="http://www.themeparktourist.com/images/facebook-icon-small.png" />
							<img width="35" height="35" alt="" src="http://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Google_Plus_Shiny_Icon.svg/256px-Google_Plus_Shiny_Icon.svg.png" />
							
							<img width="35" height="35" alt="" src="http://acmrio.org.br/engenho/wp-content/themes/Broadcast/images/twitter-icon.png" />
							
						
					</div><!-- /.col -->
					
				</div><!-- /.row --> 
			</div><!-- .container -->
		  
			
		</footer>
	
	
       <!-- <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php //echo $this->url('home') ?>"><img src="<?php //echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php //echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php //echo $this->url('home') ?>"><?php //echo $this->translate('Home') ?></a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?php //echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php //echo date('Y') ?> by Zend Technologies Ltd. <?php//echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> 
        <?php //echo $this->inlineScript() ?> 
		-->
    </body>
</html>