<script	type='text/javascript' src="<?php echo $this->basePath() . '/js/compracerta/cadastroproduto/cadastroproduto.js' ?>"></script>


<div class="row">
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Cadastro de Nota Fiscal
            </div>
            
            <div class="panel-body">
                
                <div id='error_msg' class="alert alert-danger" role="alert" style='display:none;'></div>
                
                <form id="frm_busca_nf" class="form-horizontal">
                    
                    <input id='viewState' type="hidden" name="viewState" value="<?php echo $viewState ?>" />
    
                    <input id='eventValidation' type="hidden" name="eventValidation" value="<?php echo $eventValidation ?>" />
                    
                    <input id='captchaSom' type="hidden" name="captchaSom" value="<?php echo $captchaSom ?>" />
                    
                    <input id='token' type="hidden" name="token" value="<?php echo $token ?>" />
                    
                    <div class="form-group">
                        <label class="col-sm-7 control-label">
                        
                            <img src='data:image/png;base64<?php echo $img ?>'/>
                        
                        </label>
                    </div>
                    
                    <div class="form-group">
                        <div class="col-sm-5 col-sm-offset-3">
                            <input id="captcha" name="captcha" type="text" class="form-control" placeholder="Digite a imagem">
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <div class="col-sm-7 col-sm-offset-3">
                            <input id="chave_acesso" value='52150202430968000345550060001306821712975467' name="chave_acesso" type="text" class="form-control" placeholder="Numero da nota fiscal">
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-10">
                            <button id="consulta_nf" type="submit" class="btn btn-default">Buscar Nota Fiscal</button>
                        </div>
                    </div>
                    
                </form>
                
            </div>
            
        </div>
        
    </div>
    
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Resultado
            </div>
            
            <div class="panel-body">
                
            </div>
            
        </div>
        
    </div>
    
</div>