<script	type='text/javascript' src="<?php echo $this->basePath() . '/js/compracerta/home/home.js' ?>"></script>

<form class="form-inline" id='frm_consultar' action='' method='POST'>
    
    <input id='viewState' type="hidden" name="viewState" value="<?php echo $viewState ?>" />
    
    <input id='eventValidation' type="hidden" name="eventValidation" value="<?php echo $eventValidation ?>" />
    
    <input id='captchaSom' type="hidden" name="captchaSom" value="<?php echo $captchaSom ?>" />
    
    <input id='token' type="hidden" name="token" value="<?php echo $token ?>" />

    <img src='data:image/png;base64<?php echo $img ?>'/>
    
    <input id='captcha' type="text" name="code" value="" /><br />
    
    <label>Chave acesso</label>
    
    <input id='chave_acesso'  type="text" id="chave_acesso" value="" /><br />
    
    <button id='consultar'>Consultar</button>

</form>

</br>
Resultado:</br>

<div id='resultado' style='width:70%'>
    
    
    
</div>

<?php //echo $response ?>