<?php echo $this->doctype(); 



?>

<script	type='text/javascript' src="<?php echo $this->basePath() . '/js/compracerta/index/index.js' ?>"></script>


<!--<nav>
  <ul id='paginacao' class="pagination">
    <li class="disabled">
      <a id='pg_ant' href="#" aria-label="Anterior">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <li name='pg_li' class="active"><a id='link_1' href="#">1</a></li>
    <li name='pg_li' ><a id='link_2' href="#">2</a></li>
    <li name='pg_li' ><a id='link_3' href="#">3</a></li>
    <li name='pg_li' ><a id='link_4' href="#">4</a></li>
    <li name='pg_li' ><a id='link_5' href="#">5</a></li>
    <li name='pg_li' style='display:none'><a id='link_6' href="#">6</a></li>
    <li name='pg_li' style='display:none'><a id='link_7' href="#">7</a></li>
        <li >
      <a id='pg_prox'  href="#" aria-label="Proximo">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>-->



<div class="row clearfix" style="text-align:center">
	<div class="col-md-4 column">
	
		<div class="thumbnail" height='100px;' style="display:none" id='thumbnail1'>
			<img id='img1' width="160" height="100" alt="300x200" src="" />
			<div class="caption">
				<p id='titulo1'>
				</p>
				<p id='preco1' style='color:#990000'>
				</p>
				<p>
					<a class="btn btn-primary" href="#">Cadastrar Compra</a>
				</p>
			</div>
		</div>
	</div>
	<div class="col-md-4 column">
	
		<div class="thumbnail" height='100px;' style="display:none" id='thumbnail2'>
			<img id='img2' width="160" height="100" alt="300x200" src="" />
			<div class="caption">
				<p id='titulo2'>
				</p>
				<p id='preco2' style='color:#990000'>
				</p>
				<p>
					<a class="btn btn-primary" href="#">Cadastrar Compra</a>
				</p>
			</div>
		</div>
		
	</div>
	<div class="col-md-4 column">
	
		<div class="thumbnail" height='100px;' style="display:none" id='thumbnail3'>
			<img id='img3' width="160" height="100" alt="300x200" src="" />
			<div class="caption">
				<p id='titulo3'>
				</p>
				<p id='preco3' style='color:#990000'>
				</p>
				<p>
					<a class="btn btn-primary" href="#">Cadastrar Compra</a>
				</p>
			</div>
		</div>
	</div>
</div>


<div class="row clearfix" style="text-align:center">
	<div class="col-md-4 column">
	
		<div class="thumbnail" height='100px;' style="display:none" id='thumbnail4'>
			<img id='img4' width="160" height="100" alt="300x200" src="" />
			<div class="caption">
				<p id='titulo4'>
				</p>
				<p id='preco4' style='color:#990000'>
				</p>
				<p>
					<a class="btn btn-primary" href="#">Cadastrar Compra</a>
				</p>
			</div>
		</div>
	</div>
	<div class="col-md-4 column">
	
		<div class="thumbnail" height='100px;' style="display:none" id='thumbnail5'>
			<img id='img5' width="160" height="100" alt="300x200" src="" />
			<div class="caption">
				<p id='titulo5'>
				</p>
				<p id='preco5' style='color:#990000'>
				</p>
				<p>
					<a class="btn btn-primary" href="#">Cadastrar Compra</a>
				</p>
			</div>
		</div>
		
	</div>
	<div class="col-md-4 column">
	
		<div class="thumbnail" height='100px;' style="display:none" id='thumbnail6'>
			<img id='img6' width="160" height="100" alt="300x200" src="" />
			<div class="caption">
				<p id='titulo6'>
				</p>
				<p id='preco6' style='color:#990000'>
				</p>
				<p>
					<a class="btn btn-primary" href="#">Cadastrar Compra</a>
				</p>
			</div>
		</div>
	</div>
</div>


<div class="row clearfix" style="text-align:center">
	<div class="col-md-4 column">
	
		<div class="thumbnail" height='100px;' style="display:none" id='thumbnail7'>
			<img id='img7' width="160" height="100" alt="300x200" src="" />
			<div class="caption">
				<p id='titulo7'>
				</p>
				<p id='preco7' style='color:#990000'>
				</p>
				<p>
					<a class="btn btn-primary" href="#">Cadastrar Compra</a>
				</p>
			</div>
		</div>
		
	</div>
	<div class="col-md-4 column">

		<div class="thumbnail" height='100px;' style="display:none" id='thumbnail8'>
			<img id='img8' width="160" height="100" alt="300x200" src="" />
			<div class="caption">
				<p id='titulo8'>
				</p>
				<p id='preco8' style='color:#990000'>
				</p>
				<p>
					<a class="btn btn-primary" href="#">Cadastrar Compra</a>
				</p>
			</div>
		</div>
		
	</div>
	<div class="col-md-4 column">
	
		<div class="thumbnail" height='100px;' style="display:none" id='thumbnail9'>
			<img id='img9' width="160" height="100" alt="300x200" src="" />
			<div class="caption">
				<p id='titulo9'>
				</p>
				<p id='preco9' style='color:#990000'>
				</p>
				<p>
					<a class="btn btn-primary" href="#">Cadastrar Compra</a>
				</p>
			</div>
		</div>
		
	</div>
</div>


<div class="row clearfix" style="text-align:center">
	<div class="col-md-4 column">
	
		<div class="thumbnail" height='100px;' style="display:none" id='thumbnail10'>
			<img id='img10' width="160" height="100" alt="300x200" src="" />
			<div class="caption">
				<p id='titulo10'>
				</p>
				<p id='preco10' style='color:#990000'>
				</p>
				<p>
					<a class="btn btn-primary" href="#">Cadastrar Compra</a>
				</p>
			</div>
		</div>
		
	</div>
	<div class="col-md-4 column">

		<div class="thumbnail" height='100px;' style="display:none" id='thumbnail11'>
			<img id='img11' width="160" height="100" alt="300x200" src="" />
			<div class="caption">
				<p id='titulo11'>
				</p>
				<p id='preco11' style='color:#990000'>
				</p>
				<p>
					<a class="btn btn-primary" href="#">Cadastrar Compra</a>
				</p>
			</div>
		</div>
		
	</div>
	<div class="col-md-4 column">
	
		<div class="thumbnail" height='100px;' style="display:none" id='thumbnail12'>
			<img id='img12' width="160" height="100" alt="300x200" src="" />
			<div class="caption">
				<p id='titulo12'>
				</p>
				<p id='preco12' style='color:#990000'>
				</p>
				<p>
					<a class="btn btn-primary" href="#">Cadastrar Compra</a>
				</p>
			</div>
		</div>
		
	</div>
</div>