<?php echo $this->doctype(); ?>

<nav>
  <ul class="pagination">
    <li>
      <a href="#" aria-label="Anterior">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <li><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li>
      <a href="#" aria-label="Proximo">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>


<div class="row clearfix" style="text-align:center">
	<div class="col-md-4 column">
	
		<div class="thumbnail" height='100px;'>
			<img width="160" height="100" alt="300x200" src="imageurl" />
			<div class="caption">
				<p>
					titulo1
				</p>
				<p style='color:#990000'>
					R$ preco1
				</p>
				<p>
					<a class="btn btn-primary" href="#">Localizar</a>
				</p>
			</div>
		</div>
		<div class="thumbnail" height='100px;'>
			<img width="160" height="100" alt="300x200" src="" />
			<div class="caption">
				<p>
					titulo2
				</p>
				<p style='color:#990000'>
					R$ preco2
				</p>
				<p>
					<a class="btn btn-primary" href="#">Localizar</a>
				</p>
			</div>
		</div>
	</div>
	<div class="col-md-8 column">
		
	
			<div class="thumbnail" style='height:100%;'>
				<img width="181" height="130" alt="300x200" src="" />
				<div class="caption">
					<p>
						
						titulo3
					
					</p>
					<p style='color:#990000'>
						R$ preco3

					</p>
					<p>
						<a class="btn btn-primary" href="#">Localizar</a>
					</p>
				</div>
			</div>
		
			<div class="col-md-6 column">
				<div class="thumbnail" height='100px;' width='50px;'>
					<img width="160" height="100" alt="300x200" src="" />
					<div class="caption">
						<p>
							titulo4
						</p>
						<p style='color:#990000'>
							R$ preco4
						</p>
						<p>
							<a class="btn btn-primary" href="#">Localizar</a>
						</p>
					</div>
				</div>
			</div>
			
			<div class="col-md-6 column">
				<div class="thumbnail" height='100px;' width='50px;'>
					<img width="160" height="100" alt="300x200" src="" />
					<div class="caption">
						<p>
							titulo5
						</p>
						<p style='color:#990000'>
							preco5
						</p>
						<p>
							<a class="btn btn-primary" href="#">Localizar</a>
						</p>
					</div>
				</div>
			</div>
		
	</div>
</div>


<div class="row clearfix" style="text-align:center">
	<div class="col-md-4 column">
	
		<div class="thumbnail">
			<img width="160" height="100" alt="300x200" src="" />
			<div class="caption">
				<p>
					titulo6
				</p>
				<p style='color:#990000'>
					R$ preco6

				</p>
				<p>
					<a class="btn btn-primary" href="#">Localizar</a>
				</p>
			</div>
		</div>
	</div>
	<div class="col-md-4 column">
	
		<div class="thumbnail">
			<img width="160" height="100" alt="300x200" src="" />
			<div class="caption">
				<p>
					titulo7
				</p>
				<p style='color:#990000'>
					R$ preco7

				</p>
				<p>
					<a class="btn btn-primary" href="#">Localizar</a>
				</p>
			</div>
		</div>
	</div>
	<div class="col-md-4 column">
	
		<div class="thumbnail">
			<img width="160" height="100" alt="300x200" src="" />
			<div class="caption">
				<p>
					titulo8
				</p>
				<p style='color:#990000'>
					R$ preco8

				</p>
				<p>
					<a class="btn btn-primary" href="#">Localizar</a>
				</p>
			</div>
		</div>
	</div>
</div>


<div class="row clearfix" style="text-align:center">
    
    <div class="col-md-4 column">
    
    	<div class="thumbnail">
    		<img width="160" height="100" alt="300x200" src="" />
    		<div class="caption">
    			<p>
    				titulo9
    			</p>
    			<p style='color:#990000'>
    				R$ preco9
    
    			</p>
    			<p>
    				<a class="btn btn-primary" href="#">Localizar</a>
    			</p>
    		</div>
    	</div>
    	
    </div>
    <div class="col-md-4 column">
    
    	<div class="thumbnail">
    		<img width="160" height="100" alt="300x200" src="" />
    		<div class="caption">
    			<p>
    				titulo10
    			</p>
    			<p style='color:#990000'>
    				R$ preco10
    
    			</p>
    			<p>
    				<a class="btn btn-primary" href="#">Localizar</a>
    			</p>
    		</div>
    	</div>
    	
    </div>
    <div class="col-md-4 column">
    
    	<div class="thumbnail">
    		<img width="160" height="100" alt="300x200" src="" />
    		<div class="caption">
    			<p>
    				titulo11
    			</p>
    			<p style='color:#990000'>
    				R$ preco11
    
    			</p>
    			<p>
    				<a class="btn btn-primary" href="#">Localizar</a>
    			</p>
    		</div>
    	</div>
    	
    </div>
</div>



