<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        
        <?php echo $this->headTitle('Quero')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php 
        
        	echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        
	        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
		    ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
		    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');
	    
	       	echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/less-1.3.3.min.js')
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',)); 
            
        ?>
        
        
		<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
		<script type="text/javascript" src="https://www.google.com/jsapi"></script>
		
		<style type="text/css">
	    
			.navbar-default {
				background-color: #F6F7F7;
				border-color: #F6F7F7;
			}
			
	    </style>

    </head>
<body style="background-color:#F6F7F7">
	

	<div class="col-md-12 column">
		
		<nav class="collapse navbar-collapse navbar-default" role="navigation">
			<ul class="nav navbar-nav">
			<li>
			<a style="color:#3C763D" class="navbar-brand" href="index/listaproduto">Quero</a>
			</li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
			<li><a style="color:#3C763D" href="http://expo.getbootstrap.com" onclick="ga('send', 'event', 'Navbar', 'Community links', 'Expo');">Cadastrar</a></li>
			<li><a style="color:#3C763D" href="http://blog.getbootstrap.com" onclick="ga('send', 'event', 'Navbar', 'Community links', 'Blog');">Entrar</a></li>
			</ul>
		  
			<form id='frm_busca_prod' class="form-inline navbar-right" role="form">

				<div class="form-group">
					<label class="sr-only" for="exampleInputEmail2">Produto</label>
					<input type="text" class="form-control input-lg" id="nm_produto" placeholder="Produto">
				</div>

				<button id='busca_produto' class="btn btn-success" >Localizar</button>

			</form>
		  
		</nav>
  
	</div>
	
	
	<div class="container">
			<?php echo $this->content; ?>
	</div>
	
	
    </body>
</html>
