<script type="text/javascript">

  google.load("visualization", "1", {packages:["table"]});
  google.setOnLoadCallback(drawTable);

  function drawTable() {
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Nome');
    data.addColumn('number', 'Valor Unitario');
    data.addColumn('number', 'Quantidade');
    data.addColumn('number', 'Valor total');
    /*data.addRows([
      ['Mike',  {v: 10000, f: '$10,000'}, true],
      ['Jim',   {v:8000,   f: '$8,000'},  false],
      ['Alice', {v: 12500, f: '$12,500'}, true],
      ['Bob',   {v: 7000,  f: '$7,000'},  true]
    ]);*/

    var table = new google.visualization.Table(document.getElementById('table_div'));

    table.draw(data, {showRowNumber: true, width:'100%'});
  }
</script>


<div class="row" >
    <div class="col-lg-12"></br></br>
        <!--<h1 class="page-header">Dashboard</h1>-->
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">

    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Produtos Cadastrados
            </div>
            <div class="panel-body">
                
                <div id="table_div"></div>
                
            </div>
        </div>
    </div>

</div>
        