<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
    	
    	<meta charset="utf-8">
    	<meta content="IE=edge" http-equiv="X-UA-Compatible">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        
        
        <?php echo $this->headTitle('Quero')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php 
        
        	echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        
	        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
		    ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
		    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');
	    
	       	echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/less-1.3.3.min.js')
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',)); 
            
        ?>
        
        
        
		<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() . '/css/layout.css' ?>">
		<style type="text/css">
			

			
	    </style>

    </head>
<body style="background-color:#F6F7F7">
	
	
	<header role="banner" class="navbar navbar-default navbar-fixed-top " data-scroll-header="">
        <div class="container">
            <div class="navbar-header">
                <button data-target=".main-navigation" data-toggle="collapse" class="navbar-toggle" type="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="#top" data-scroll="" class="navbar-brand">
                    <!--<img height="60" alt="logo" src="<?//php echo $this->basePath() . '/logo.png' ?>" class="">-->
                    Econoom
                </a>
            </div>
            <div class="collapse navbar-collapse main-navigation">

                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#top" data-scroll="">Home</a>
                    </li>
                    <li>
                        <a href="#services" data-scroll="">Serviços</a>
                    </li>
                    
                </ul>
            </div>
        </div>
    </header>
    
    <?php echo $this->content; ?>	
    
    
    <footer id="site-footer">
        <section>
            <div class="container">
                <div class="section-content row">
                    <div class="col-md-3 col-sm-6">
                        <aside class="widget wow bounceInUp animated" style="visibility: visible;">
                            <div class="widget-header">
                                <h4>Sobre</h4>
                            </div>
                            <p>Desenvolvimento de softwares de qualidade e segurança visando o lucro e a economia do usuário. <a href="#">More →</a>
                            </p>
                            <address>
                                <strong>Econoom</strong>
                                <br>Brasil 
                                <br>Goiania, Go
                                <br>
                                <abbr title="Phone">Tel:</abbr>(62) 8252 - 6149
                            </address>
                        </aside>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <aside class="widget wow bounceInUp animated" style="visibility: visible;">
                            <div class="widget-header">
                                <h4>Latest from Blog</h4>
                            </div>
                            <ul class="post-list">
                                <li>
                                    <div class="details">
                                        <h5 class="title"><a rel="bookmark" href="post.html">Incididunt occaecat officia nostrud ullamco officia.</a>
                                          </h5>
                                        <div class="meta">December 27, 2013</div>
                                    </div>
                                </li>
                                <li>
                                    <div class="details">
                                        <h5 class="title"><a rel="bookmark" href="post.html">Aliqua sunt dolore pariatur et quis non ex ad in dolore officia.</a>
                                          </h5>
                                        <div class="meta">December 26, 2013</div>
                                    </div>
                                </li>
                                <li>
                                    <div class="details">
                                        <h5 class="title"><a rel="bookmark" href="post.html">Consectetur magna dolor tempor elit occaecat in commodo.</a>
                                          </h5>
                                        <div class="meta">December 25, 2013</div>
                                    </div>
                                </li>
                            </ul>
                        </aside>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <aside class="widget wow bounceInUp animated" style="visibility: visible;">
                            <div class="widget-header">
                                <h4>Comunicação</h4>
                            </div>
                            <ul class="list-inline footer-social">
                                <li>
                                    <a href="#">
                                        <img alt="" src="">
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <img alt="" src="">
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <img alt="" src="">
                                    </a>
                                </li>
                            </ul>
                        </aside>
                        <aside class="widget wow bounceInUp animated" style="visibility: visible;">
                            <div class="widget-header">
                                <h4>Twitter Feeds</h4>
                            </div>
                            <div data-count="1" data-username="twitter" class="tweets">
                                <ul class="tweet_list">
                                    <li class="tweet_first tweet_odd">
                                        <span class="tweet_text">RT 
                                            <span class="at">@</span>
                                            <a href="http://twitter.com/ICC">ICC</a> NEW! Hashflags! Support your 
                                            <a class="tweet_hashtag" href="https://twitter.com/search?q=%23cwc15">#cwc15</a>
                                            team on Android and Web! 
                                            <a class="tweet_hashtag" href="https://twitter.com/search?q=%23AFG">#AFG</a>, 
                                            <a class="tweet_hashtag" href="https://twitter.com/search?q=%23AUS">#AUS</a>, 
                                            <a class="tweet_hashtag" href="https://twitter.com/search?q=%23BAN">#BAN</a>, 
                                            <a class="tweet_hashtag" href="https://twitter.com/search?q=%23ENG">#ENG</a>, 
                                            <a class="tweet_hashtag" href="https://twitter.com/search?q=%23IND">#IND</a>, 
                                            <a class="tweet_hashtag" href="https://twitter.com/search?q=%23IRE">#IRE</a>, 
                                            <a class="tweet_hashtag" href="https://twitter.com/search?q=%23NZ">#NZ</a>, 
                                            <a class="tweet_hashtag" href="https://twitter.com/search?q=%23PAK">#PAK</a>, 
                                            <a class="tweet_hashtag" href="https://twitter.com/search?q=%23ZIM">#ZIM</a>, 
                                            <a class="tweet_hashtag" href="https://twitter.com/search?q=%23SA">#SA</a>, 
                                            <a class="tweet_hashtag" href="https://twitter.com/search?q=%23SCO">#SCO</a>, 
                                            <a class="tweet_hashtag" href="https://twitter.com/search?q=%23SL">#SL</a>, 
                                            <a class="tweet_hashtag" href="https://twitter.com/search?q=%23UAE">#UAE</a>, 
                                            <a class="tweet_hashtag" href="https://twitter.com/search?q=%23WI">#WI</a>
                                        </span>
                                        <span class="tweet_time">
                                            <a title="view tweet on twitter" 
                                            href="http://twitter.com/twitter/status/570851757154152449">about 5 hours ago</a>
                                        </span>
                                    </li>
                                </ul>
                            </div>
                        </aside>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <aside class="widget wow bounceInUp animated" style="visibility: visible;">
                            <div class="widget-header">
                                <h4>
                                    <img data-wow-delay="0.9s" class="mailchimp-img wow bounceInDown animated" alt="" src="" 
                                    style="visibility: visible;-webkit-animation-delay: 0.9s; -moz-animation-delay: 0.9s; animation-delay: 0.9s;">
                                    &nbsp;MailChimp Newsletter
                                </h4>
                            </div>
                            <div class="footer-newsletter">
                                <p>Subscribe to our weekly Newsletter and stay tuned to all our updates, offers, freebies and more.</p>
                                <form class="subscription" method="post" id="mc-form" action="#" novalidate="true">
                                    <div class="input-group">
                                        <input type="email" id="mc-email" placeholder="Your email address" class="form-control" name="EMAIL">
                                        <span class="input-group-btn">
                                            <button class="btn btn-primary" type="submit" role="button"><i class="fa fa-check"></i>
                                            </button>
                                        </span>
                                    </div>
                                    <p class="small text-muted text-center">We promise we wont sell your email address.</p>
                                    <label class="text-danger text-center mc-label" for="mc-email"></label>
                                </form>
                            </div>
                        </aside>
                    </div>
                </div>
            </div>
        </section>
        
        <section id="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-md-7 col-sm-6">
                        <img class="footer-logo" alt="novelty-logo" src="">
                        <p class="copyright">
                            &copy; 2015 | Econoom foi desenvolvido por Sebastiao Junio.
                        </p>
                    </div>
                    <div class="col-md-5 pt20 col-sm-6">
                        <nav class="text-right pull-right" id="footer-nav">
                            <ul class="list-inline">
                                <li><a href="#">Termos</a>
                                </li>
                                <li><a href="#">Politica de Privacidade</a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </section>
    </footer>
	
	
    </body>
</html>
