
<html>
	
	<head>
        <meta charset="utf-8">
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        
        <?php echo $this->headTitle('Quero')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php 
        
        	echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        
	        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
		    ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
		    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');
	    
	       	echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/less-1.3.3.min.js')
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',)); 
            
        ?>
        
        
		<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
		<script type="text/javascript" src="https://www.google.com/jsapi"></script>
		
		<style type="text/css">
	    
			.navbar-default {
				background-color: #F6F7F7;
				border-color: #F6F7F7;
			}
			
	    </style>

    </head>
	
	<body>
		<?php echo $this->content; ?>
		
	</body>
	
</html>